version: "3"
services:
    server:
        image: darrylyan46/chip-db:express-server
        ports:
         - "3000:3000"
        depends_on:
        - "database"
    client:
        image: darrylyan46/chip-db:angular-cli
        ports:
         - "4200:4200"
        depends_on:
        - "server"
    database:
        image: 'mongo'
        ports:
         - "27017:27017"
